openapi: 3.0.0
info:
  title: Airport Terminals API
  description: An OpenAPI definition for accessing airport terminals via IACO
  version: 1.0.0

servers:
  - url: https://portfolio-eight-lac-63.vercel.app/api
    description: Main

paths:
  /test:
    get:
      summary: Test Request
      description: Very simple request
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: "test"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: "Unauthorized access."

  /sfo:
    get:
      summary: Get SFO Terminals
      description: Get terminal information for San Francisco International Airport
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    terminal:
                      type: string
              example:
                - "Terminal 1"
                - "Terminal 2"
                - "Terminal 3"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: "Unauthorized access."